info:
  component: Config Samples
  description: Spring Cloud Samples
  url: https://github.com/guslcho/springCloud
endpoints:
  restart:
    enabled: true
logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
    
server:
  port: 8080