info:
  component: Config Samples add test component
  description: Spring Cloud Samples x
  url: https://github.com/guslcho/springCloud
endpoints:
  restart:
    enabled: true
eeee

eeee
eeelogging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
    
server:
  port: 8080